// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-Pa5kbzxq7enAb-mQMwPG4ZZXFBybfM',
    appId: '1:936209742885:web:e8582f6b280572598c13cc',
    messagingSenderId: '936209742885',
    projectId: 'ormeal',
    authDomain: 'ormeal.firebaseapp.com',
    storageBucket: 'ormeal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK8F6dH30uG91PekR6owtSgL4F7BMRubA',
    appId: '1:936209742885:android:bd377f283997ea2f8c13cc',
    messagingSenderId: '936209742885',
    projectId: 'ormeal',
    storageBucket: 'ormeal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7-kugjVBVJm7cAeJOgZMSKpZMwQ2Boo',
    appId: '1:936209742885:ios:c76d8ca4da8c1cbd8c13cc',
    messagingSenderId: '936209742885',
    projectId: 'ormeal',
    storageBucket: 'ormeal.appspot.com',
    iosBundleId: 'com.example.ormeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7-kugjVBVJm7cAeJOgZMSKpZMwQ2Boo',
    appId: '1:936209742885:ios:2a81969f334415308c13cc',
    messagingSenderId: '936209742885',
    projectId: 'ormeal',
    storageBucket: 'ormeal.appspot.com',
    iosBundleId: 'com.example.ormeal.RunnerTests',
  );
}
